--con PL/SQL VAMOS A PODER CREAR
--BLOQUES PL/SQL: QUE SON BLOQUES DE CODIGO QUE PUEDEN EJECUTAR SETENCIAS(BLOQUE ANONIMO)
--DECLRACIONES(OPCIONAL): EN DONDE SE DECLARAN CONSTANTES , VARIABLES Y CURSORES, QUE SE UTILIZAN EN EL BLOQUE 
--INSTRUCCIONES: CONTIENEN LAS SENTENCIAS A EJECUTAR
--EXCEPCIONES: SE PUEDE CAPTURAR EXCEPCIONES DEL SITEMA 
/* SINTAXIS
        DECLARE | IS/AS
        BEGIN(INICIA EL BLOQUE)
        
        
        ......
        EXCEPCIONES
        END
*/

DECLARE --DECLARACION DE VARIIABLES, CONSTANTES Y CURSORES
LV_VARIABLE NUMBER := 0;

BEGIN --DONDE INICIA LA EJECUCION DE SENTENCIAS
    DBMS_OUTPUT.PUT_LINE('HOLA DESDE BLOQUE ANONIMO PL/SQL');
END; --CIERRO MI BLOQUE 
/ -- HASTA AQUI SE EJECUTA. INDICADOR 



--USO DE CICLOS CON PL/SQL
DECLARE 
LV_VARIABLE NUMBER :=0;
BEGIN 
    LOOP
        DBMS_OUTPUT.PUT_LINE('VALOR: ' ||LV_VARIABLE);
        LV_VARIABLE := LV_VARIABLE + 1; --ASIGNACION :=
        --EXIT WHEN LV_VARIABLE =11;
        IF LV_VARIABLE = 10
            THEN EXIT;
        END IF;
    END LOOP;
END;
/

--USO DE CICLO FOR Y LOOP
DECLARE
BEGIN
--FOR 
    FOR i IN 1..10
        LOOP
            DBMS_OUTPUT.PUT_LINE('VALOR DE LA VARIABLE FOR: ' || i);
            EXIT WHEN i = 6;
        END LOOP;
END;
/

--USO DE WHILE Y LOOP
DECLARE 
LV_ITERATOR NUMBER := 1;
BEGIN
    WHILE LV_ITERATOR <= 6
        LOOP
            DBMS_OUTPUT.PUT_LINE('VALOR DEL ITERATOR CON WHILE: ' || LV_ITERATOR);
            LV_ITERATOR := LV_ITERATOR + 1;
        END LOOP;
END;
/

--USO DE VARIABLES BOOLEANAS
DECLARE
LV_VALIDADOR BOOLEAN := FALSE;
BEGIN 
    FOR i IN 1..20
        LOOP
            DBMS_OUTPUT.PUT_LINE('VALOR DEL ITERATOR: ' || i);
            IF i = 9 THEN
                LV_VALIDADOR := TRUE;
            END IF;
            EXIT WHEN LV_VALIDADOR;
        END LOOP;
END;
/

--EJERCICIO EN UN BLOQUE PL/SQL LA IMPRESION EN CONSOLA DE:
--NOMBRE COMPLETO, CARRERA, ESTADO DONDE VIVE
--IMPRIMIR LAS TABLAS DE MULTIPLICAR DEL 1 AL 10.
--EJE TABLE DEL 1
--1*1 = 1

DECLARE

BEGIN
    
    DBMS_OUTPUT.PUT_LINE('ALINE MORALES '  );

    DBMS_OUTPUT.PUT_LINE('SISTEMAS COMPUTACIONALES ');
    
    DBMS_OUTPUT.PUT_LINE('PUEBLA');
        FOR i in 1..10
        LOOP 
        DBMS_OUTPUT.PUT_LINE('TABLA DEL: ' || i );
                FOR j in 1..10
                    LOOP 
                    DBMS_OUTPUT.PUT_LINE (i || 'X' || j || ' = ' || (i * j));
                    END LOOP;
        END LOOP;
    
END;
/

        
        
        
        
        
        
        
        