/* SENTENCIA CASE 
CASE 
  WHEN CONDICION_1 THEN RESULTADO_1 
  WHEN CONDICION_2 THEN RESULTADO_2
  ....
  ELSE RESULTADO_PREDETERMINADO
END 
*/

--CREAR UN DDL DE LA ENTIDAD LIBRO
CREATE TABLE LIBRO(
  ID_LIBRO NUMBER,
  NOMBRE NVARCHAR2(100),
  AUTOR NVARCHAR2(100),
  GENERO NUMBER, --1. DRAMA 2. TERROR 3. CIENCIA 4. NOVELA 5. THIRLLER 6. COMEDIA
  NO_PAGINAS NUMBER,
  PRECIO NUMBER,
  EDITORIAL NVARCHAR2(100),
  CONSTRAINT LIBRO_PK PRIMARY KEY(ID_LIBRO)
);

INSERT INTO LIBRO VALUES(1, 'FLORES EN EL ATICO', 'VC.ANDREWS', 0, 600, 550, 'DE BOLSILLO');
INSERT INTO LIBRO VALUES (2,'IT','STEPHEN KING',2,250,350,'GARCIA');
INSERT INTO LIBRO VALUES (3, 'CEMENTERIO DE ANIMALES', 'STEVEN', 0, 550, 750, 'DE BOLSILLO');
INSERT INTO LIBRO VALUES(4, 'LA LADRONA DE LIBROS', 'ELENA MARQUEZ', 1, 250, 600, 'COMETA');
INSERT INTO LIBRO VALUES (5,'CRONICA DE UNA MUERTE ANUNCIADA','GABRIEL GARCIA MARQUEZ',0,350,250,'ALFAGUARA');
INSERT INTO LIBRO VALUES(6, 'LA CASA DE LAS SOMBRAS', 'TRAD. SIMON SAITO', 2, 600, 750, 'MINOTAURO');
COMMIT;

SELECT * FROM LIBRO;

--USO DE SENTENCIA CASE 
SELECT 
ID_LIBRO,
NOMBRE,
AUTOR,
(
CASE GENERO
WHEN 1 THEN 'DRAMA'
WHEN 2 THEN 'TERROR'
WHEN 3 THEN 'CIENCIA FICCION'
WHEN 4 THEN 'NOVELA'
WHEN 5 THEN 'THRILLER'
WHEN 6 THEN 'COMEDIA'
ELSE 'SIN GENERO'
END
) AS GENERO, NO_PAGINAS, PRECIO, EDITORIAL FROM LIBRO;

---

SELECT
ID_LIBRO,
NOMBRE,
PRECIO,
AUTOR,
GENERO,
NO_PAGINAS,
(
CASE 
WHEN PRECIO >400 THEN 'ES CARO' || TO_CHAR(PRECIO, '9,999.00') || 'PESOS'
WHEN PRECIO <= 400 THEN 'ES BARATO'||TO_CHAR(PRECIO, '9,999.00')|| 'PESOS'
ELSE 'PRECIO NO DEFINIDO'
END
) AS PRECIO, EDITORIAL FROM LIBRO; 