--DDL DE PADRE
CREATE TABLE PADRE(
ID_PADRE NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDO NVARCHAR2(100),
EDAD NUMBER,
TRABAJO NVARCHAR2(100),
CONSTRAINT PADRE_PK PRIMARY KEY (ID_PADRE)
);

INSERT INTO PADRE VALUES (1, 'BRAULIO', 'GRAJALES', 65, 'DOCENTE');
INSERT INTO PADRE VALUES (2, 'RICARDO', 'MORALES', 0, 'NULL');
INSERT INTO PADRE VALUES (3,'JOEL','GRAHAM',45 ,'CONTADOR');
INSERT INTO PADRE VALUES (4,'RICHAR','LOREZ',35 ,'CHEF');
INSERT INTO PADRE VALUES (5, 'EMILY', 'GOMEZ', 26, 'CONTADORA');
INSERT INTO PADRE VALUES (6, 'CESAR', 'CARRILLO', 35, 'DOCTOR');
INSERT INTO PADRE VALUES (7, 'URIEL', 'MARTINEZ', 32, 'ABOGADO');
INSERT INTO PADRE VALUES (8, 'PAMELA', 'SANCHEZ', 32, 'REPORTERA');
INSERT INTO PADRE VALUES (9, 'ELENA', 'ROSAS', 30, 'CAPTURISTA');
INSERT INTO PADRE VALUES (10, 'MIGUEL', 'SANCHEZ', 25, 'PROMOTOR');
INSERT INTO PADRE VALUES (11,'JUAN', 'ROJAS',48, 'INGENIERO');
INSERT INTO PADRE VALUES (12,'KARINA', 'ROJAS',38,'ABOGADA');
COMMIT;

SELECT * FROM PADRE;

CREATE TABLE HIJO(
ID_HIJO NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDO NVARCHAR2(100),
EDAD NUMBER,
HOBBIE NVARCHAR2(100),
PADRE_ID NUMBER,
CONSTRAINT HIJO_PK PRIMARY KEY(ID_HIJO),
CONSTRAINT PADRE_FK FOREIGN KEY (PADRE_ID) REFERENCES PADRE(ID_PADRE)
--CONSTRAINT ES UNA PALABRA RESERVADA + NOMBRE DE CONSTRAINT(UNICO), TIPO DE CONSTRAINT + CAMPO QUE SERA LA CLAVE FORANEA +ANNOTATIONS +
--REFERENCIAS ES PALABRA RESERVADA + EL NOMBRE DE LA TABLA Y EL CAMPO AL QUE SE HACE REFERENCIA PARA RELACIONARLA CON LA TABLA PADRE
);


INSERT INTO HIJO VALUES (1,'MIRANDA','GRAJALES',27,'LEER NOVELAS',1);
INSERT INTO HIJO VALUES (2,'DAVID','HERNANDEZ',7,'JUGAR A LAS ESCONDIDAS',NULL);
INSERT INTO HIJO VALUES (3,'MARK','GRAJAM',26,'ENTRENAR',1);
INSERT INTO HIJO VALUES (4,'OLIVER','HERNANDEZ',6,'JUGAR CON SOLDADOS',NULL);
INSERT INTO HIJO VALUES (5, 'CAMILA', 'PEREZ', '77', 'CANTAR', 3);
INSERT INTO HIJO VALUES (6, 'SANSA', 'STARK', '25', 'ROBAR TRONOS', 4);
INSERT INTO HIJO VALUES (7, 'YUNUEN','ROJAS',22, 'GUSTA DE BEBER PIÑAS COLADAS',11);
INSERT INTO HIJO VALUES (8,'DARIEN ', 'ROJAS',4, 'LEER CUENTOS',4);
INSERT INTO HIJO VALUES (9, 'MARIO', 'GALLEGOS', 19, 'JUGAR VIDEOJUEGOS', 3);
INSERT INTO HIJO VALUES (10, 'GABY', 'MARTINEZ', 15, 'MAQUILLARSE', 2);
INSERT INTO HIJO VALUES (11, 'ALONDRA', 'MARTINEZ', 17, 'VER SERIES', 3);
INSERT INTO HIJO VALUES (12, 'ROBERTO', 'SANCHEZ', 7, 'JUGAR VIDEOJUEGOS', 4);

--USO DE INNER JOIN --NOS DEVUELVE LOS REGISTROS QUE TIENEN VALORES COINCIDENTES EN AMBAS TABLAS 
SELECT * FROM HIJO H
INNER JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--USO DEL LEFT JOIN -- DEVULEVE TODOS LOS REGISTROS DE LA TABLA IZQUIERDA (HIJO) Y LOS REGISTROS COINCIDENTES DE LA TABLA DERECHA (PADRE)
SELECT * FROM HIJO H
LEFT JOIN PADRE P 
ON H.PADRE_ID = P.ID_PADRE;

--USO DEL LEFT JOIN QUITANDO COINCIDENCIAS 
SELECT * FROM HIJO H 
LEFT JOIN PADRE P 
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;

--USO DEL RIGHT JOIN -- DEVUELVE TODOS LOS REGISTROS DE LA TABLA DERECHA QUE ES LA TABLA (PADRE)Y LOS REGISTROS COINCIDENTES CON LA TABLA IZQUIERDA QUE ES LA (HIJO)
SELECT * FROM HIJO H
RIGHT JOIN PADRE P 
ON H.PADRE_ID = P.ID_PADRE;

--USO DEL RIGHT JOIN SIN CONINCIDENCIAS 
SELECT * FROM HIJO H 
RIGHT JOIN PADRE P 
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;

--USO DEL FULL JOIN -- DEVUELVE TODOS LOS REGISTROS DE AMBAS TABLAS Y SUS COINCIDENCIAS 

SELECT * FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--USO DEL FULL JOIN SIN COINCIDENCIAS
SELECT * FROM HIJO H 
FULL JOIN PADRE P 
ON H.PADRE_ID = P.ID_PADRE 
WHERE H.PADRE_ID IS NULL;