--AGREGAR REGISTROS A MI TABLA EMPLEADO 
INSERT INTO EMPLEADO VALUES(1, 'MACARIO', 'PALMA', 22, 'CONTADOR', 'DEPARTAMENTO DE FINANZAS');
INSERT INTO EMPLEADO VALUES(2,'RODRIGO','HERNANDEZ',35,'INGENIERO','DEPARTAMENTO DE REDES');
INSERT INTO EMPLEADO VALUES(3,'JUANITO', 'PEREZ',25, 'COINTROL DE CALIDAD', 'DEPARTAMENT DE CALIDAD');
INSERT INTO EMPLEADO VALUES(4, 'NAHUM', 'ROSAS', 20, 'INGENIERO', 'MANTENIMIENTO');
INSERT INTO EMPLEADO VALUES(5, 'MARCOS', 'ENRIQUEZ', 59, 'ABOGADO', 'DEPARTAMENTO FAMILIAR');


COMMIT;
SELECT * FROM EMPLEADO;

--FUNCIONES 

--MODIFICAR O CAMBIAR EL NOMBRE DE LA COLUMNA 
ALTER TABLE EMPLEADO RENAME COLUMN APELLIDO__P TO APELLIDO_PATERNO;
UPDATE EMPLEADO SET NOMBRE = 'JUANIX' WHERE ID_EMPLEADO = 3;

--ORDER BY 
SELECT * FROM EMPLEADO ORDER BY EDAD ASC;
--O
SELECT * FROM EMPLEADO ORDER BY EDAD DESC;

--BUSQUEDA DE INFORMACION CON CARACTER 
--BUSCAR EMPLEADOS QUE EMPIEZAN CON LA LETRA A
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'J%';
--BUSCAR EMPLEADO QUE SU NOMBRE CONTENGA LETRA I
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%H%';
--BUSCAR EMPLEADOS QUE SU NOMBRE TERMINE CON LA LETRA O
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%O';

--BUSCAR EMPLEADOS QUE SU NOMBRE NO SEA NULL
SELECT * FROM EMPLEADO WHERE NOMBRE IS NOT NULL;

--USO DE LA TABLA DUAL
SELECT 5 + 5 AS SUMA FROM DUAL;

--USO DE LA FUNCION LENGHT
SELECT LENGTH('ESTA ES UNA CADENA DE PRUEBA PARA EL USO DE LENGTH')AS TAMINIO FROM DUAL;

--BUSCAR CON MAS CONDICIONES 
--BUSCAR EMPLEADOS QUE SEAN MAYORES A 25
SELECT * FROM EMPLEADO WHERE EDAD > 25;
--BUSCAR LOS EMPLEADOS MENORES DE 30 CON ORDEN ACENDENTE
SELECT * FROM EMPLEADO WHERE EDAD <30 ORDER BY EDAD ASC;
--BUSCAR QUE SEAN MAYORES DE 24 Y MENORES DE 28
SELECT * FROM EMPLEADO WHERE EDAD > 24 AND EDAD < 28;
--RANGO BETWEEN 
SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 30 AND 25;
--BUSCAR LOS EMPLEADOS CON EL ID 1,3,5;
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO = 1 OR ID_EMPLEADO = 3 OR ID_EMPLEADO = 5;
--USO DE LA FUNCION IN 
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1,2,5);

--USO DE LA FUNCION GROUP BY Y COUNT 
SELECT DEPARTAMENTO FROM EMPLEADO GROUP BY DEPARTAMENTO;
SELECT DEPARTAMENTO, COUNT(ID_EMPLEADO) AS NO_EMPLEADO FROM EMPLEADO WHERE DEPARTAMENTO IS NOT NULL GROUP BY DEPARTAMENTO;

--CONTAR LOS EMPLEADOS QUE TENGAS MAS DE 26
SELECT COUNT(ID_EMPLEADO) AS TOTAL_EMPLEADO FROM EMPLEADO WHERE EDAD > 25;

--FUNCION DE AGREGACION SUM 
SELECT SUM(ID_EMPLEADO) AS SUMA_EDADES FROM EMPLEADO WHERE APELLIDO_PATERNO LIKE '%A%';

--FUNCION DE AGREGACION MAX
SELECT MAX(EDAD) AS EDAD_MAXIMA FROM EMPLEADO;
--FUNCION DE AGREGACION MIN 
SELECT MIN(EDAD) AS EDAD_MINIMA FROM EMPLEADO;

--FUNCION DDE AGREGACION AVG 
SELECT AVG(EDAD) EDAD_PROMEDIO FROM EMPLEADO;

--USO DE LA OPCION ROUND 
SELECT ROUND(AVG(EDAD), 2) AS PRIMEDIO_EDAD FROM EMPLEADO;
--USO DE TO CHAR CON FORMATO PODAMOS COLOCAR UN FORMATO A LA IMPRESION EDAD
SELECT TO_CHAR(AVG(EDAD), 'fm99.0') AS PROMEDIO_EDAD FROM EMPLEADO;

--DAR UN FORMATO DIFERENTE 
-- FUNCION CONCAT
SELECT CONCAT(CONCAT(CONCAT(CONCAT('EL EMPLEADO',' '), NOMBRE), ' '), APELLIDO_PATERNO) AS DETALLE FROM EMPLEADO;
--USO DE PIPE O BARRA VERTICAL ----> 
SELECT 'EL EMPLEADO' || NOMBRE || '' || APELLIDO_PATERNO || 'DE EDAD' ||EDAD || 'ANIOS, TRABAJA EN EL DEPARTAMENTO'|| DEPARTAMENTO || 'COMO' || PUESTO AS DETALLE FROM EMPLEADO;

--SUB CONSULTA 
SELECT * FROM EMPLEADO WHERE 
EDAD = (
SELECT MIN(EDAD)
FROM EMPLEADO
WHERE DEPARTAMENTO = 'RH'
);

SELECT * FROM EMPLEADO WHERE 
EDAD = (
SELECT MAX(EDAD)
FROM EMPLEADO
WHERE DEPARTAMENTO = ('RH'
)
)AND DEPARTAMENTO = 'RH';