CREATE TABLE JUEGOS(
  ID_JUEGOS NUMBER,
  NOMBRE NVARCHAR2(100),
  CONSOLA NUMBER, -- 1 PLAY STATION 2. XBOX 3. NINTENDO 4. SEGA 5.GAME BOY
  GENERO NVARCHAR2(100),
  PRECIO NUMBER,
  COLOR NVARCHAR2(100),
  FORMATO NVARCHAR2(100),
  CONSTRAINT JUEGOS_PK PRIMARY KEY (ID_JUEGOS)
);

INSERT INTO JUEGOS VALUES (1,'GOOD OF WAR',1,'ACCION',600,'AZUL','DISCO');
INSERT INTO JUEGOS VALUES (2,'GEARS',2,'ACCION',650,'VERDE','DISCO');
INSERT INTO JUEGOS VALUES (3,'MARIO BROS',3,'FAMILIAR',800,'ROJO','CASET');
INSERT INTO JUEGOS VALUES (4,'GHOST OF TUSHIMA',0,'ACCION',700,'MORADO','DIGITAL');
INSERT INTO JUEGOS VALUES (5,'POKEMON ROJO',5,'AVENTURA',300,'GRIS','CASET');
INSERT INTO JUEGOS VALUES (6,'TERRARIA',4,'CONSTRUCCION',100,'VERDE','DIGITAL');
COMMIT;

SELECT * FROM JUEGOS;

SELECT 
ID_JUEGOS,
NOMBRE,
(
CASE CONSOLA

WHEN 1 THEN 'PLAY STATION'
WHEN 2 THEN 'XBOX'
WHEN 3 THEN 'NINTENDO'
WHEN 4 THEN 'SEGA'
WHEN 5 THEN 'GAME BOY'
ELSE 'CONSOLA NO REGISTRADA'
END
)AS CONSOLA, PRECIO, COLOR, FORMATO FROM JUEGOS;

SELECT 
ID_JUEGOS,
NOMBRE,
CONSOLA,
GENERO,
PRECIO,
(
CASE 
WHEN PRECIO > 500 THEN 'NO ME ALCANZA TA CARO' || TO_CHAR(PRECIO, '$9,999,00') || ' DOLARES'
WHEN PRECIO <= 400 THEN 'OFERTON ESTA BARATO' || TO_CHAR(PRECIO, '$9,999.00')|| ' DOLARES'
ELSE 'PRECIO NO ENCONTRADO'
END
) AS PRECIO, COLOR , FORMATO FROM JUEGOS;

SELECT 
  ID_JUEGOS,
  NOMBRE,
  GENERO,
  PRECIO,
  COLOR,
  FORMATO,
  CASE 
    WHEN GENERO = 'ACCION' THEN 'Juegos de combate'
    WHEN GENERO = 'FAMILIAR' THEN 'Juegos para toda la familia'
    WHEN GENERO = 'AVENTURA' THEN 'Juegos de exploración'
    WHEN GENERO = 'CONSTRUCCION' THEN 'Juegos de construcción'
    ELSE 'Otros géneros'
  END AS CATEGORIA_GENERO
FROM 
  JUEGOS;

SELECT 
  ID_JUEGOS,
  NOMBRE,
  PRECIO,
  CASE 
    WHEN PRECIO > 500 THEN 'Nuevo'
    WHEN PRECIO <= 500 THEN 'Usado'
    ELSE 'Estado no especificado'
  END AS ESTADO_DEL_JUEGO
FROM 
  JUEGOS;

