--Creacion de una entidad con DDL
/*
CHAR : ALAMACENA DATOS DE LONGITUD
CHARACTER: 
VARCHAR: 
VARCHAR2: SOLO ORACLE
NVARCHAR2: ESPECIFICO DE ORACLE, SE UTILIZA PARA ALAMACENAR CARACTERES DE LONGITUD VARIABLE DE CARACTER UNICIO
*/

--DDL
CREATE TABLE EMPLEADO(
  ID_EMPELADO NUMBER,
  NOMBRE NVARCHAR2(100),
  APELLIDO_P NVARCHAR2(100),
  EDAD NUMBER,
  PUESTO NVARCHAR2(100),
  DEPARTAMENTO NVARCHAR2(100)
);

--DML
INSERT INTO EMPLEADO VALUES(1,'JULIAN','RPFRIGUEZ',37,'ENCARGADO DE NOMINAS','RH');
COMMIT;--UNA VEZ QUE SE EJECUTA UNA SENTENCIA DML DEBEMOS CONFIRMAR LOS CAMBIOS PARA TERMINAR CON LA TRANSACCION DE MI TABLA
--SI UNA TRANSACCION SE QUEDA SIN CONFIRMAR LA BD SE QUEDARA BLOQUEADA POR EL USUARIO QUE REALIZOP  Y NINGUN OTRO USUARIO PODRA
--REALIZAR OPERACION DE PERSISTENCIAS

SELECT * FROM EMPLEADO;

--EJECUTAR UN DML PARA ELIMINAR LOS REGISTROS DE UNA TABLA 
DELETE FROM EMPLEADO;--ELIMINA LOS REGISTROS EN MI TABLA 
--EJECUTAR UN DDL PARA ELIMINAR UNA TABLA 
DROP TABLE EMPLEADO;--ELIMINAR TODA LA TABLA 

--USO DE LOS CONTRAINT 
--CREAR UNA ENTIDAD CON PRIMARY KEY --> PRIMERA FORMA 
CREATE TABLE EMPELADO(
ID_EMEPEADO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100),
APELIDO_P NVARCHAR2(100),
EDAD NUMBER,
PUESTO NVARCHAR2(100),
DEPARTAMENTO NVARCHAR2(100)
);

--DDL CON PRIMARY KEY SEGUNDA FORMA 
CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDO__P NVARCHAR2(100),
EDAD NUMBER,
PUESTO NVARCHAR2(100),
DEPARTAMENTO NVARCHAR2(100),
PRIMARY KEY(ID_EMEPLEADO)
);

--DDL CON PRIMARY KEY TERCERA FORMA
CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDO__P NVARCHAR2(100),
EDAD NUMBER,
PUESTO NVARCHAR2(100),
DEPARTAMENTO NVARCHAR2(100),
CONSTRAINT EMPLEADO_PK PRIMARY KEY(ID_EMPLEADO)
);