SET SERVEROUTPUT ON;


--1 REALIZAR UNA FUNCION QUE CALCULE EL AREA DEL CIRCULO Y QUE RECIBA COMO PARAMETRO EL RADIO
CREATE OR REPLACE FUNCTION FN_AREA_CIRCULO(P_RADIO IN NUMBER)
RETURN NUMBER
IS
  LV_AREA NUMBER;
BEGIN
  
  LV_AREA := 3.14159 * P_RADIO * P_RADIO;  
  
  RETURN LV_AREA;  -- Devolvemos el valor del área como un número
END FN_AREA_CIRCULO;
/
BEGIN 
  DBMS_OUTPUT.PUT_LINE('EL AREA DEL CIRCULO CON RADIO 5 ES: ' || FN_AREA_CIRCULO(5)); 
END;
/

--2 CREAR UNA FUNCION LLAMADA FN_ES_PRIMO QUE RECIBA COMO PARAMETRO UN NUMERO Y DEVUELVA EL MENSAJE INDICANDO SI ES UN NUMERO PRIMO

CREATE OR REPLACE FUNCTION FN_ES_PRIMO(P_NUMERO IN NUMBER)
RETURN NVARCHAR2
IS
LV_RESULTADO NVARCHAR2(100);
I NUMBER;
BEGIN
IF P_NUMERO <=1 THEN 
LV_RESULTADO := 'EL NUMERO'|| P_NUMERO || ' NO ES PRIMO';
RETURN LV_RESULTADO;
END IF;

FOR I IN 2..P_NUMERO - 1 LOOP
IF MOD (P_NUMERO, I ) = 0 THEN 
LV_RESULTADO := 'EL NUMERO' || P_NUMERO || ' NO ES PRIMO';
RETURN LV_RESULTADO;
END IF;
END LOOP;

LV_RESULTADO := 'EL NUMERO' || P_NUMERO || ' ES PRIMO';
RETURN LV_RESULTADO;
END FN_ES_PRIMO;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE(FN_ES_PRIMO(8));  
  DBMS_OUTPUT.PUT_LINE(FN_ES_PRIMO(5));  
END;
/

--CREAR UNA FUNCION LLAMADA FN_NUMERO_MES QUE RECIBA UN NUMERO DEL 1 AL 12 Y DEVUELVA EL NOOMBRE DEL MES CORRESPONDIENTE EN ESPAÑOL 
--(EJEMPLO)= 1 CORRESPONDE A ENERO 

CREATE OR REPLACE FUNCTION FN_NUMERO_MES(P_NUMERO IN NUMBER)
RETURN NVARCHAR2
IS
LV_MES NVARCHAR2(25);
BEGIN 
CASE P_NUMERO
WHEN 1 THEN LV_MES := 'ENERO';
WHEN 2 THEN LV_MES := 'FEBRERO';
WHEN 3 THEN LV_MES := 'MARZO';
WHEN 4 THEN LV_MES := 'ABRIL';
WHEN 5 THEN LV_MES := 'MAYO';
WHEN 6 THEN LV_MES := 'JUNIO';
WHEN 7 THEN LV_MES := 'JULIO';
WHEN 8 THEN LV_MES := 'AGOSTO';
WHEN 9 THEN LV_MES := 'SEPTIEMBRE';
WHEN 10 THEN LV_MES := 'OCTUBRE';
WHEN 11 THEN LV_MES := 'NOVIEMBRE';
WHEN 12 THEN LV_MES := 'DICIEMBRE';
ELSE 
LV_MES := 'NUMERO INVALIDO';
END CASE;

RETURN LV_MES;
END FN_NUMERO_MES;
/

BEGIN 
DBMS_OUTPUT.PUT_LINE(FN_NUMERO_MES(5));
DBMS_OUTPUT.PUT_LINE(FN_NUMERO_MES(10));
DBMS_OUTPUT.PUT_LINE(FN_NUMERO_MES(25));
END;
/

--4 CREA UNA FUNCION QUE CONVIERTA LA TEMPERATURA DE GRADOS CELSIUS A FARENHEIT (F = (C * 9/5)+ 32) 
CREATE OR REPLACE FUNCTION FN_CELSIUS_FAHRENHEIT(P_CELSIUS IN NUMBER)
RETURN NUMBER
IS
  LV_FAHRENHEIT NUMBER;
BEGIN

  LV_FAHRENHEIT := (P_CELSIUS * 9 / 5) + 32;
  
  RETURN LV_FAHRENHEIT;  
END FN_CELSIUS_FAHRENHEIT;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('LA TEMPERATURA DE FAHRENHEIT ES DE: ' || FN_CELSIUS_FAHRENHEIT(35));  
  DBMS_OUTPUT.PUT_LINE('LA TEMPERATURA DE FAHRENHEIT ES DE: ' || FN_CELSIUS_FAHRENHEIT(0));   
  DBMS_OUTPUT.PUT_LINE('LA TEMPERATURA DE FAHRENHEIT ES DE: ' || FN_CELSIUS_FAHRENHEIT(-15)); 
END;
/



