--FUNCIONES SON BLOQUES PL/SQL QUE REALIZAN UNA TAREA EN ESPECIFICO 

--CREAR FUNCION 
CREATE OR REPLACE FUNCTION FN_NUMERO_PAR(P_NUMERO IN NUMBER)
RETURN NVARCHAR2
IS
LV_RESULTADO NVARCHAR2(100);
BEGIN
--INSTRUCCIONES 
--PARAMETRO DIVISIBLE ENTRE 2 
IF MOD(P_NUMERO, 2)= 0 THEN 
LV_RESULTADO := 'EL NUMERO: ' || P_NUMERO || 'ES PAR';
ELSE 
LV_RESULTADO := 'EL NUMERO: ' || P_NUMERO || ' NO ES PAR';
END IF;
RETURN LV_RESULTADO;
END FN_NUMERO_PAR;
/

BEGIN
DBMS_OUTPUT.PUT_LINE(FN_NUMERO_PAR(10));
END;
/

SELECT FN_NUMERO_PAR(9) FROM DUAL;


/*
1 REALIZAR UNA FUNCION QUE CALCULE EL AREA DEL CIRCULO Y QUE RECIBA COMO PARAMETRO EL RADIO
2 CREAR UNA FUNCION LLAMADA FN_ES_PRIMO QUE RECIBA COMO PARAMETRO UN NUMERO Y DEVUELVA EL MENSAJE INDICANDO SI ES UN NUMERO PRIMO 
3 CREAR UNA FUNCION LLAMADA FN_NUMERO_MES QUE RECIBA UN NUMERO DEL 1 AL 12 Y DEVUELVA EL NOOMBRE DEL MES CORRESPONDIENTE EN ESPAÑOL 
(EJEMPLO)= 1 CORRESPONDE A ENERO 
4 CREA UNA FUNCION QUE CONVIERTA LA TEMPERATURA DE GRADOS CELSIUS A FARENHEIT (F = (C * 9/5)+ 32) 
*/

SET SERVEROUTPUT ON;
--PARA ENCENDER LA FUNCION
SET SERVEROUTPUT ON;


CREATE OR REPLACE FUNCTION FN_AREA_CIRCULO(P_RADIO IN NUMBER)
RETURN NUMBER
IS
  LV_AREA NUMBER;
BEGIN
  
  LV_AREA := 3.14159 * P_RADIO * P_RADIO;  
  
  RETURN LV_AREA;  -- Devolvemos el valor del área como un número
END FN_AREA_CIRCULO;
/
BEGIN 
  DBMS_OUTPUT.PUT_LINE('EL AREA DEL CIRCULO CON RADIO 5 ES: ' || FN_AREA_CIRCULO(5)); 
END;
/