CREATE OR REPLACE PACKAGE BODY PKG_GENERAL AS
-- FUNCION 
FUNCTION FN_NUMERO_PAR(P_NUMERO IN NUMBER)
RETURN VARCHAR2 -- Cambié NVARCHAR2 por VARCHAR2
IS
  LV_RESULTADO VARCHAR2(100); -- Cambié NVARCHAR2 por VARCHAR2
BEGIN
  --INSTRUCIONES
  --EL PARAMETRO ES DIVISIBLE ENTRE 2
  IF MOD(P_NUMERO, 2) = 0 THEN
    LV_RESULTADO := 'EL RESULTADO: ' || P_NUMERO || ' ES PAR';
  ELSE 
    LV_RESULTADO := 'EL NUMERO: ' || P_NUMERO || ' NO ES PAR';
  END IF;
  RETURN LV_RESULTADO;
END FN_NUMERO_PAR;

----- PROCEDURE
PROCEDURE PR_DETALLE_LIBRO
IS
  CURSOR LIBRO_INFO IS
    SELECT NOMBRE,
           (
             CASE GENERO
               WHEN 1 THEN 'DRAMA' 
               WHEN 2 THEN 'TERROR'
               WHEN 3 THEN 'CIENCIA FICCION' -- Corregí el error tipográfico en "CIENCIA FICCIONE"
               WHEN 4 THEN 'NOVELA'
               WHEN 5 THEN 'THRILLER'
               WHEN 6 THEN 'COMEDIA'
               ELSE 'SIN GENERO'
             END
           ) AS GENERO,
           PRECIO 
    FROM LIBRO;
  
  -- VARIABLES LOCALES
  LV_NOMBRE LIBRO.NOMBRE%TYPE;
  LV_GENERO VARCHAR2(100); -- Cambié NVARCHAR2 por VARCHAR2
  LV_PRECIO NUMBER;
  
BEGIN
  OPEN LIBRO_INFO;
  -- RECUPERAR EL CURSOR Y MOSTRAR LOS DATOS
  LOOP
    -- POR CADA FILA RECORRIDA SE TOMARAN LOS DATOS DEL CURSOR
    FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
    
    -- CONDICION PARA SALIR CUANDO EL CURSOR YA NO TENGA REGISTROS
    EXIT WHEN LIBRO_INFO%NOTFOUND;
    
    -- MOSTRAR LOS DATOS DEL CURSOR
    DBMS_OUTPUT.PUT_LINE('NOMBRE DEL LIBRO: ' || LV_NOMBRE || ', GENERO: ' || LV_GENERO || ', PRECIO: ' || LV_PRECIO);
  END LOOP;
  
  -- CERRAR EL CURSOR
  CLOSE LIBRO_INFO;
END PR_DETALLE_LIBRO;
END PKG_GENERAL;
/
