--CREACION DE DDL TABLA 
CREATE TABLE AUTOMOVIL(
ID_AUTO NUMBER,
MARCA NVARCHAR2(100),
SUB_MARCA NVARCHAR2(100),
MODELO NUMBER,
COLOR NVARCHAR2(100),
PRECIO NVARCHAR2(100),
VERSION NVARCHAR2(100),
CONSTRAINT AUTOMOVIL_PK PRIMARY KEY(ID_AUTO)
);

INSERT INTO AUTOMOVIL VALUES(1,'NISSAN','SENTRA',2001,'NEGRO',230000,'AUSTERA');
INSERT INTO AUTOMOVIL VALUES(2,'ZENTRONO','SOG',2014,'MORADO',530000,'FURY');
INSERT INTO AUTOMOVIL VALUES(3,'ASTRO','RG',2020,'BLANCO',630000,'AVO');
INSERT INTO AUTOMOVIL VALUES(4,'AUDI', 'R8', 2020, 'ROJO', 700000, 'DEPORTIVO');
INSERT INTO AUTOMOVIL VALUES(5,'VOCHO', 'VOCHO', 1993, 'NARANJA', 80000, 'PEQUENO');
INSERT INTO AUTOMOVIL VALUES(6,'CHEVROLET', 'CAVALIER', 2023, 'AZUL', 250500, 'NORMAL');
INSERT INTO AUTOMOVIL VALUES(7,'FORT', 'MUSTANG', 2000, 'NEGRO', 346930, 'DEPORTIVO');
INSERT INTO AUTOMOVIL VALUES(8,'HONDA', 'CIVIC', 2004, 'NEGRO', 530000, 'DEPORTIVO');
INSERT INTO AUTOMOVIL VALUES(9,'TOYOTA', 'SIENNA', 2014, 'AZUL', 700000, 'FAMILIAR');
COMMIT;

SELECT * FROM AUTOMOVIL;

-- EJERCICIO NO 1 mostrar precio mayor a menor agregar $ separados por ',' los miles con 2 decimales 
SELECT 
    ID_AUTO,
    MARCA,
    SUB_MARCA,
    MODELO,
    COLOR,
    VERSION,
    TO_CHAR(PRECIO, '$999,999,999.00') AS PRECIO
FROM AUTOMOVIL
ORDER BY PRECIO DESC;

-- EJERCICIO 2 busca la sub marca con la letra E y sacar el promedio y darle formato

SELECT 
    SUB_MARCA,
    TO_CHAR(ROUND(AVG(PRECIO), 2), '$999,999,999.00') AS PROMEDIO_PRECIO
FROM AUTOMOVIL
WHERE SUB_MARCA LIKE '%E%'
GROUP BY SUB_MARCA;

--EJERCICIO 3 mostrar autos que cuesten 7.000 o mas y cambiar las letras a minusculas de la marca y submarca

SELECT 
    LOWER(MARCA) AS MARCA_MINUSCULA,
    LOWER(SUB_MARCA) AS SUB_MARCA_MINUSCULA,
    PRECIO
FROM AUTOMOVIL
WHERE PRECIO >= ('7,000');

--EJERCICIO 4 consultar que los registros no sean nulos que su precio sea mayor a 500mil y ordenar de menor a mayor 
SELECT 
    ID_AUTO,
    MARCA,
    SUB_MARCA,
    MODELO,
    COLOR,
    PRECIO,
    VERSION
FROM AUTOMOVIL
WHERE VERSION IS NOT NULL
  AND PRECIO > 500000
ORDER BY PRECIO ASC;

--EJERCICIO 5 mostrar los automoviles que sus precios sean mayores a 500mil y menores a 800mil
SELECT * FROM AUTOMOVIL WHERE PRECIO > 500000 AND PRECIO < 800000;

--EJERCICIO 6 busca los autos que sean color negro y agregar $ y palabra PESOS 
SELECT
    MARCA,
    COLOR,
    TO_CHAR(PRECIO, '$999,999,999.00') || ' PESOS' AS PRECIO_FORMATO
FROM AUTOMOVIL 
WHERE COLOR LIKE '%NEGRO';

--EJERCICIO 7 contar cunatos autos tengo en cada marca e indicar la marca a la que pertenece
SELECT 
    MARCA, 
    COUNT(MARCA) AS NO_AUTOS 
FROM AUTOMOVIL 
WHERE MARCA IS NOT NULL 
GROUP BY MARCA;

--EJERCICIO 8 mostra el registro que tenga el precio mas alto y dar un formato al precio 
SELECT 
    ID_AUTO,
    MARCA,
    SUB_MARCA,
    MODELO,
    COLOR,
    TO_CHAR(PRECIO, '$999,999,999.00') AS PRECIO_FORMATO,
    VERSION
FROM AUTOMOVIL
WHERE PRECIO = (SELECT MAX(PRECIO) FROM AUTOMOVIL);

--EJERCICIO 9 MOSTRAR EL AUTO MAS ANTIGUO AGREGAR FORMATO AL PRECIO Y ASIGNAR PALABRA (AÑO)
SELECT 
    ID_AUTO,
    MARCA,
    SUB_MARCA,
    'AÑO ' || MODELO AS AÑO_MODELO,
    COLOR,
    TO_CHAR(PRECIO, '$999,999,999.00') AS PRECIO_FORMATO,
    VERSION
FROM AUTOMOVIL
WHERE MODELO = (SELECT MIN(MODELO) FROM AUTOMOVIL);

--EJERCICIO 10 DESGLOSE EL DETALLE DE LOS AUTOS CON (CONTACT O PIPE)
SELECT CONCAT(CONCAT(CONCAT(CONCAT(CONCAT('EL AUTOMOVIL ', MARCA), ' '), SUB_MARCA), ' '), 
    CONCAT(CONCAT(CONCAT('AÑO ', MODELO), ' '), TO_CHAR(PRECIO, '$999,999,999.00'))) AS DETALLE
FROM AUTOMOVIL;
