CREATE TABLE PERRO(
ID_PERRO NUMBER , 
NOMBRE NVARCHAR2(100) ,
RAZA NVARCHAR2(100) ,
EDAD NUMBER , 
COLOR NVARCHAR2(100) ,
CONSTRAINT PERRO_PK PRIMARY KEY (ID_PERRO)
);

INSERT INTO PERRO VALUES (1,'ZEUS','FRENCH',5,'BLANCO');
INSERT INTO PERRO VALUES (2,'HADES','FRENCH',5,'NEGRO');
INSERT INTO PERRO VALUES (3, 'ROCY', 'LABRADOR', 8, 'GRIS');
INSERT INTO PERRO VALUES (4, 'MAX', 'BULLDOG', 9, 'NEGRO');
INSERT INTO PERRO VALUES (5, 'ROCKY', 'BEAGLE', 6, 'MARRÓN');
INSERT INTO PERRO VALUES (6, 'LUNA', 'LABRADOR', 4, 'AMARILLO');
INSERT INTO PERRO VALUES (7, 'BELLA', 'POODLE', 8, 'BLANCO');
INSERT INTO PERRO VALUES (8, 'MILO', 'DACHSHUND', 7, 'GRIS');
INSERT INTO PERRO VALUES (9, 'COCO', 'CHIHUAHUA', 7, 'CREMA');
INSERT INTO PERRO VALUES (10, 'RUBY', 'GOLDEN RETRIEVER', 6, 'DORADO');
INSERT INTO PERRO VALUES (11, 'LUCKY', 'PUG', 7, 'BEIGE');
INSERT INTO PERRO VALUES (12, 'OLIVER', 'BOXER', 5, 'ATÍPICO');
COMMIT;

CREATE TABLE CACHORRO(
ID_CACHORRO NUMBER , 
NOMBRE NVARCHAR2(100) ,
RAZA NVARCHAR2(100) ,
EDAD NUMBER ,
TAMAÑO NVARCHAR2(100) ,
PERRO_ID NUMBER ,
CONSTRAINT CACHORRO_PK PRIMARY KEY (ID_CACHORRO),
CONSTRAINT PERRO_FK FOREIGN KEY (PERRO_ID) REFERENCES PERRO (ID_PERRO)
);

INSERT INTO CACHORRO VALUES (1,'JOSE','BULL',1,'1.2',NULL);
INSERT INTO CACHORRO VALUES (2, 'BONGO', 'DALMATIAN', 2, '0.8', 1);
INSERT INTO CACHORRO VALUES (3, 'FREYA', 'BEAGLE', 3, '1.1', NULL);
INSERT INTO CACHORRO VALUES (4, 'OLGA', 'SHEPHERD', 4, '1.3', 1);
INSERT INTO CACHORRO VALUES (5, 'ZIGGY', 'BORDER COLLIE', 2, '1.0', NULL);
INSERT INTO CACHORRO VALUES (6, 'LUNA', 'POODLE', 1, '0.9', 12);
INSERT INTO CACHORRO VALUES (7, 'MILO', 'BULTERIER', 5, '1.4', 7);
INSERT INTO CACHORRO VALUES (8, 'MAYA', 'MALTIPOO', 3, '1.0', 6);
INSERT INTO CACHORRO VALUES (9, 'SANTI', 'GREAT DANE', 4, '1.5', 5);
INSERT INTO CACHORRO VALUES (10, 'TESS', 'CHIHUAHUA', 1, '0.7', 4);
INSERT INTO CACHORRO VALUES (11, 'RICO', 'DACHSHUND', 2, '1.0', 3);
INSERT INTO CACHORRO VALUES (12, 'NINA', 'CAVALIER KING CHARLES', 3, '1.1', 11);
COMMIT;




----INNER JOIN 

SELECT * FROM CACHORRO C
INNER JOIN PERRO P
ON C.PERRO_ID = P.ID_PERRO;

----LEFT JOIN

SELECT * FROM CACHORRO C
LEFT JOIN PERRO P 
ON C.PERRO_ID = P.ID_PERRO;

SELECT * FROM CACHORRO C 
LEFT JOIN PERRO P 
ON C.PERRO_ID = P.ID_PERRO
WHERE C.PERRO_ID IS NULL;

----RIGHT JOIN

SELECT * FROM CACHORRO C
RIGHT JOIN PERRO P 
ON C.PERRO_ID = P.ID_PERRO;

SELECT * FROM CACHORRO C 
RIGHT JOIN PERRO P 
ON C.PERRO_ID = P.ID_PERRO
WHERE C.PERRO_ID IS NULL;

-----FUL JOIN

SELECT * FROM CACHORRO C
FULL JOIN PERRO P
ON C.PERRO_ID = P.ID_PERRO;

SELECT * FROM CACHORRO C 
FULL JOIN PERRO P 
ON C.PERRO_ID = P.ID_PERRO 
WHERE C.PERRO_ID IS NULL;

