CREATE TABLE BOTELLAS_PRD(
    ID_BOTELLA NUMBER,
    TIPO NVARCHAR2(100),
    COLOR NVARCHAR2(100),
    VOLUMEN NUMBER,
    PRECIO NUMBER,
    CONSTRAINT BOTELLAS_PRD_PK PRIMARY KEY(ID_BOTELLA)
);

SELECT * FROM BOTELLAS;

INSERT INTO BOTELLAS VALUES(1,'CERVEZA','AZUL',650,500);
INSERT INTO BOTELLAS VALUES(2,'WHISKY','CAFE',1650,5000);
INSERT INTO BOTELLAS VALUES(3,'RON','ROJO',750,800);
INSERT INTO BOTELLAS VALUES(4,'MARGARITA','BLANCO',150,600);
INSERT INTO BOTELLAS VALUES(5,'VINO','ROSA',1250,700);
INSERT INTO BOTELLAS VALUES(6,'CARAJILLO','CAFE',950,700);
INSERT INTO BOTELLAS VALUES(7,'MOJITO','BLANCO',350,900);
INSERT INTO BOTELLAS VALUES(8,'TEQUILA','AMARILLO',1350,1500);

CREATE OR REPLACE PROCEDURE PK_RESPALDO_BOTELLAS
IS 
BEGIN

DELETE FROM BOTELLAS_PRD;

INSERT INTO BOTELLAS_PRD(ID_BOTELLA,TIPO,COLOR,VOLUMEN,PRECIO)
SELECT ID_BOTELLA,TIPO,COLOR,VOLUMEN,PRECIO FROM BOTELLAS;
END PK_RESPALDO_BOTELLAS;
/

SELECT * FROM BOTELLAS;
SELECT * FROM BOTELLAS_PRD;

EXECUTE PK_RESPALDO_BOTELLAS;