--CREAR DDL
CREATE TABLE COMPUTADORA(
  ID_COMPU NUMBER, 
  MARCA NVARCHAR2(100),
  MODELO NVARCHAR2(100),
  RAM NUMBER,
  PROCESADOR NVARCHAR2(100),
  PRECIO NVARCHAR2(100),
  CONSTRAINT COMPU_PK PRIMARY KEY(ID_COMPU)
);



CREATE TABLE COMPUTADORA_PRD(
  ID_COMPU NUMBER, 
  MARCA NVARCHAR2(100),
  MODELO NVARCHAR2(100),
  RAM NUMBER,
  PROCESADOR NVARCHAR2(100),
  PRECIO NVARCHAR2(100),
  CONSTRAINT COMPU_PRD_PK PRIMARY KEY(ID_COMPU)
);

SELECT * FROM COMPUTADORA;

INSERT INTO COMPUTADORA VALUES (1, 'DELL', 'INSPIRON', 16, 'INTEL CORE i5', 110000);
INSERT INTO COMPUTADORA VALUES (2, 'LENOVO', 'THINK PAD', 8, 'INTEL CORE i3', 120000);
INSERT INTO COMPUTADORA VALUES (3, 'HP', 'INSPIRON', 8, 'TYZEN 3', 7859);
INSERT INTO COMPUTADORA VALUES (4, 'OCELOT', 'RAMSTER', 10, 'INTEL CORE i5', 17859);
INSERT INTO COMPUTADORA VALUES (5, 'AZUS', 'VIVO', 16, 'INTEL CORE i3 12TH', 9159);
INSERT INTO COMPUTADORA VALUES (6, 'MACK', 'MACBOOKAIR', 16, 'CORE I5', 30000);
INSERT INTO COMPUTADORA VALUES (7, 'TOSHIBA', 'NB350', 8, 'CORE 5', 15000);
INSERT INTO COMPUTADORA VALUES (8, 'SAMSUNG', 'X50', 32, 'INTEL CORE i7', 50000);
COMMIT;

CREATE OR REPLACE PROCEDURE PR_RESPALDO_COMPUTADORA
IS
BEGIN

DELETE FROM COMPUTADORA_PRD;

INSERT INTO COMPUTADORA_PRD(ID_COMPU,MARCA,MODELO,RAM,PROCESADOR,PRECIO)
SELECT ID_COMPU,MARCA,MODELO,RAM,PROCESADOR,PRECIO FROM COMPUTADORA;
END PR_RESPALDO_COMPUTADORA;
/

SELECT * FROM COMPUTADORA;
SELECT * FROM COMPUTADORA_PRD;

--EJECUTAR EL PROCEDIMIENTO ALMCENADO 
EXECUTE PR_RESPALDO_COMPUTADORA;

