--TRIGGER SIMPLE
--DDL PARA ENTIDAD COMPUTADORA
CREATE TABLE COMPUTADORA(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PK PRIMARY KEY(ID_COMPU)
);

-- DDL PARA LA ENTIDAD BITACORA DE COMPUTADORA QUE REGISTRARA CADA EVENTO EN LA TABLA COMPUTADORA
CREATE TABLE BIT_COMPUTADORA(
    ID_BIT NUMBER, --CLAVE PRIMARIA 
    
    --VALORES NUEVOS
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    
    --VALORES OLD
    MARCA_OLD NVARCHAR2(100),
    MODELO_OLD NVARCHAR2(100),
    RAM_OLD NUMBER,
    PROCESADOR_OLD NVARCHAR2(100),
    PRECIO_OLD NUMBER,
    
    --CAMPOS DE CONTROL
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    
    CONSTRAINT BIT_COMPU_PK PRIMARY KEY (ID_BIT)
);

CREATE OR REPLACE TRIGGER TR_I_COMPUTADORA
AFTER INSERT ON COMPUTADORA
FOR EACH ROW
DECLARE
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(100);
LV_FECHA DATE;
    BEGIN
    SELECT USER INTO LV_USUARIO FROM DUAL; --OBTNER USUARIO
    SELECT SYSDATE INTO LV_FECHA FROM DUAL; --OBTENER FECHA
    SELECT NVL(MAX(ID_BIT), 0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA; --OBTENER ID VALIDO
    
    INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD,
    USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES(LV_ID_BIT, :NEW.ID_COMPU, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, NULL,NULL, 0, NULL, 0,
        LV_USUARIO, LV_FECHA, 'INSERT');
END TR_I_COMPUTADORA;
/

--SENTENCIA S PARA LA RECUPERACION DE INFORMACION PARA CAMPOS DE CONTROL
--SENTENCIA PARA RECUOERAR EL USUARIOA ACTUAL
SELECT USER FROM DUAL;
--SENTENCIA PARA RECUPERAR LA FECHHA ACTUAL
SELECT SYSDATE FROM DUAL;
--CAMBIBAR EL FORMATO DE MI FECHA --> HORA
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YY HH24:MI:SS';

SELECT * FROM BIT_COMPUTADORA;
INSERT INTO BIT_COMPUTADORA VALUES(1);
SELECT COUNT(*) + 1 FROM BIT_COMPUTADORA;
SELECT NVL(MAX(ID_BIT),0) + 1 FROM BIT_COMPUTADORA;
SELECT  FILA_ORIGINAL, FILA_ORIGINAL + 1 AS FILA_INCREMENTADA FROM (SELECT COUNT(*) AS FILA_ORIGINAL FROM BIT_COMPUTADORA);


--PRUEBAS
INSERT INTO COMPUTADORA VALUES(1, 'HP', 'PAVILON', 16, 'INTEL CORE i9 12th', 20000);

SELECT *  FROM COMPUTADORA;
SELECT * FROM BIT_COMPUTADORA;

--EJERCICIO: REALIZAR EL TRIGGER PARA ACTUALIZAR(UPDATE) , Y PARA ELIMINAR(DELETE) EN LA MISMA BITACORA BIT_COMPUTADORA;
