--TRIGER A NIVEL SENTENCIA 
DELETE FROM COMPUTADORA; 
DELETE FROM BIT_COMPUTADORA;

CREATE OR REPLACE TRIGGER TR_I_U_D_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA
DECLARE
 LV_ID_BIT NUMBER;
 LV_USUARUIO NVARCHAR2(100);
 LV_FECHA DATE;
 LV_MOV NVARCHAR2(100);
 BEGIN
 
 SELECT S_ID_BIT_COMPU.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM FUAL;
 
 IF INSERTING THEN 
 LV_MOV := 'INSERT';
 ELSIF UPDATING THEN 
 LV_MOV := 'UPDATE';
 ELSIF DELETING THEN 
 LV_MOV := 'DELETE';
 END IF; 
 INSERT INTO BIT_COMPUTADORA(ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO)
 VALUES(LV_ID_BIT,LV_USUARIO,LV_FECHA,LV_MOV);
 END TR_I_U_D_COMPUTADORA;
 /
 
 INSERT INTO COMPUTADORA VALUES (1,'DELL','INSPIRON',16,'INTEL CORE i5',110000);
 INSERT INTO COMPUTADORA VALUES (2,'LENOVO','THINK PAD',8,'INTEL CORE i3',120000);
 INSERT INTO COMPUTADORA VALUES (3,'HP','INSPIRON',8,'TYZEN 3',7859);
 
 SELECT * FROM COMPUTADORA;
 SELECT ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO FROM BIT_COMPUTADORA;
 DELETE FROM BIT_COMPUTADORA;
 
 
 CREATE SEQUENCE S_ID_BIT_COMPU START WITH 1 INCREMENT BY 1;

CREATE TABLE BIT_COMPUTADORA (
    ID_BIT NUMBER PRIMARY KEY,
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100)
);

CREATE SEQUENCE S_ID_BIT_COMPU 
START WITH 1 
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_I_U_D_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(100);
BEGIN
    -- Obtener los valores para el registro de auditoría
    LV_ID_BIT := S_ID_BIT_COMPU.NEXTVAL;  -- Asegúrate de que la secuencia exista
    LV_USUARIO := USER;
    LV_FECHA := SYSDATE;

    -- Determinar el tipo de operación (INSERT, UPDATE, DELETE)
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;

    -- Insertar en la tabla BIT_COMPUTADORA
    INSERT INTO BIT_COMPUTADORA (ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
END TR_I_U_D_COMPUTADORA;
/

CREATE TABLE COMPUTADORA (
    ID_COMPUTADORA NUMBER PRIMARY KEY,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER
);

SELECT ID_AUDITORIA, USUARIO, FECHA_MOV, MOVIMIENTO
FROM AUDITORIA_BOTELLAS;
DELETE FROM AUDITORIA_BOTELLAS;
