CREATE TABLE BOTELLAS (
    ID_BOTELLA NUMBER PRIMARY KEY,
    TIPO NVARCHAR2(100),
    COLOR NVARCHAR2(100),
    VOLUMEN NUMBER,
    PRECIO NUMBER
);

CREATE TABLE AUDITORIA_BOTELLAS (
    ID_AUDITORIA NUMBER PRIMARY KEY,
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    ID_BOTELLA NUMBER,
    TIPO NVARCHAR2(100),
    COLOR NVARCHAR2(100),
    VOLUMEN NUMBER,
    PRECIO NUMBER
);

CREATE SEQUENCE S_ID_AUDITORIA_BOTELLAS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_I_U_D_BOTELLAS
AFTER INSERT OR UPDATE OR DELETE ON BOTELLAS
FOR EACH ROW
DECLARE
    LV_ID_AUDITORIA NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(100);
BEGIN
    
    LV_ID_AUDITORIA := S_ID_AUDITORIA_BOTELLAS.NEXTVAL;
    LV_USUARIO := USER;  
    LV_FECHA := SYSDATE; 

    
    IF INSERTING THEN
        LV_MOV := 'INSERT';
        
        INSERT INTO AUDITORIA_BOTELLAS (
            ID_AUDITORIA, USUARIO, FECHA_MOV, MOVIMIENTO,
            ID_BOTELLA, TIPO, COLOR, VOLUMEN, PRECIO
        )
        VALUES (
            LV_ID_AUDITORIA, LV_USUARIO, LV_FECHA, LV_MOV,
            :NEW.ID_BOTELLA, :NEW.TIPO, :NEW.COLOR, :NEW.VOLUMEN, :NEW.PRECIO
        );
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
        
        INSERT INTO AUDITORIA_BOTELLAS (
            ID_AUDITORIA, USUARIO, FECHA_MOV, MOVIMIENTO,
            ID_BOTELLA, TIPO, COLOR, VOLUMEN, PRECIO
        )
        VALUES (
            LV_ID_AUDITORIA, LV_USUARIO, LV_FECHA, LV_MOV,
            :NEW.ID_BOTELLA, :NEW.TIPO, :NEW.COLOR, :NEW.VOLUMEN, :NEW.PRECIO
        );
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
        
        INSERT INTO AUDITORIA_BOTELLAS (
            ID_AUDITORIA, USUARIO, FECHA_MOV, MOVIMIENTO,
            ID_BOTELLA, TIPO, COLOR, VOLUMEN, PRECIO
        )
        VALUES (
            LV_ID_AUDITORIA, LV_USUARIO, LV_FECHA, LV_MOV,
            :OLD.ID_BOTELLA, :OLD.TIPO, :OLD.COLOR, :OLD.VOLUMEN, :OLD.PRECIO
        );
    END IF;

END TR_I_U_D_BOTELLAS;
/


SELECT * FROM BOTELLAS;
INSERT INTO BOTELLAS (ID_BOTELLA, TIPO, COLOR, VOLUMEN, PRECIO)
VALUES (1, 'Vino Tinto', 'Rojo', 750, 15);

INSERT INTO BOTELLAS (ID_BOTELLA, TIPO, COLOR, VOLUMEN, PRECIO)
VALUES (2, 'Cerveza', 'Ambar', 500, 8);

INSERT INTO BOTELLAS (ID_BOTELLA, TIPO, COLOR, VOLUMEN, PRECIO)
VALUES (3, 'Agua Mineral', 'Transparente', 1000, 3);

INSERT INTO BOTELLAS (ID_BOTELLA, TIPO, COLOR, VOLUMEN, PRECIO)
VALUES (4, 'Vino Blanco', 'Amarillo', 750, 18);

INSERT INTO BOTELLAS (ID_BOTELLA, TIPO, COLOR, VOLUMEN, PRECIO)
VALUES (5, 'Ron', 'Claro', 1000, 25);

INSERT INTO BOTELLAS (ID_BOTELLA, TIPO, COLOR, VOLUMEN, PRECIO)
VALUES (6, 'CAGUAMA', 'NEGRA', 12000, 35);


UPDATE BOTELLAS
SET PRECIO = 20, VOLUMEN = 800
WHERE ID_BOTELLA = 2;

SELECT * FROM BOTELLAS; 

SELECT ID_AUDITORIA, USUARIO, FECHA_MOV, MOVIMIENTO
FROM AUDITORIA_BOTELLAS;
DELETE FROM BOTELLAS;
