--VISTAS O VIEWS -- SON UNA ALTERNATIVA PARA VISUALIZAR LOS DATOS O MAS TABLAS CREANDO UNA TABLA VIRTUAL 
--PORQUE USAMOS VISTAS?
--SON UTILIS PARA RESTRINGIR EL ACCESO DIRECTO A LA BASE DE DATOS Y TAMBIEN PERMITE REALIZAR CONSULTAS DE MANERA SENCILLA 

SELECT * FROM PADRE;
SELECT * FROM HIJO;

--VISTA 
CREATE OR REPLACE VIEW V_PADRE_HIJO_DETALLE
AS
SELECT H.ID_HIJO, H.NOMBRE, H.APELLIDO, H.EDAD, NVL(H.HOBBIE, 'SIN HOBBY') AS HOBBIE, NVL(H.PADRE_ID,0)AS PADRE
FROM HIJO H LEFT JOIN PADRE P ON H.PADRE_ID = P.ID_PADRE;
----EN LAS VIEWS NO ES NECESARIO EL END PORQUE NO ES NECESARIO CERRAR

--CONSULTAMOS LA VISTA
SELECT * FROM V_PADRE_HIJO_DETALLE;

--EJERCICIO: CREAR UNA VISTA CON LA ENTIDAD MATERIA- ALUMNO, UTILIZANDO FULL JOIN USAR MANEJADOR DE NULOS (SIN,0)

SELECT * FROM MATERIA;
SELECT * FROM ALUMNO;

CREATE OR REPLACE VIEW V_MATERIA_ALUMNO
AS
SELECT A.ID_ALUMNO,A.NOMBRE,A.APELLIDO,A.EDAD, NVL (A.CARRERA, 'NO TIENE CARRERA')AS CARRERA, NVL(A.MATERIA_ID, 0)AS MATERIA
FROM ALUMNO A FULL JOIN MATERIA M ON A.MATERIA_ID = M.ID_MATERIA;

SELECT * FROM V_MATERIA_ALUMNO;

CREATE OR REPLACE VIEW V_MATERIA_ALUMNO AS
SELECT 
    A.ID_ALUMNO,
    A.NOMBRE,
    A.APELLIDO,
    A.EDAD,
    CASE 
        WHEN A.CARRERA = 1 THEN 'SISTEMAS'
        WHEN A.CARRERA = 2 THEN 'INFORMATICA'
        WHEN A.CARRERA = 3 THEN 'MEDICINA'
        WHEN A.CARRERA = 5 THEN 'DERECHO'
        ELSE 'NO TIENE CARRERA' 
    END AS CARRERA,
    CASE 
        WHEN M.DOCENTE = 1 THEN 'JESUS'
        WHEN M.DOCENTE = 2 THEN 'MARIANA'
        WHEN M.DOCENTE = 3 THEN 'DANIEL'
        WHEN M.DOCENTE = 4 THEN 'ALAN'
        WHEN M.DOCENTE = 5 THEN 'ARMANDO'
        WHEN M.DOCENTE = 6 THEN 'JOSUE'
        ELSE 'SIN DOCENTE' 
    END AS DOCENTE,
    NVL(A.MATERIA_ID, 0) AS MATERIA -- RECORDATORIO: ESTE ES EL MANEJADOR DE LUNOS 
FROM 
    ALUMNO A 
FULL JOIN 
    MATERIA M ON A.MATERIA_ID = M.ID_MATERIA;